name: options-mispricing-engine
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11
  - pip
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - scikit-learn>=1.3.0
  - plotly>=5.18.0
  - jupyterlab>=4.0.0
  - python-dotenv>=1.0.0
  - statsmodels>=0.14.0
  - arch>=6.0.0
  - tqdm>=4.65.0
  - pytest>=7.4.0
  - pandas-datareader>=0.10.0
  - requests
  - matplotlib
  - seaborn
  - kaleido
  - pyarrow
  - pip:
    - polygon-api-client>=1.12.0
    - py_vollib>=1.0.2 